version: '3.8'

services:
  fastapi_app:
    image: izjenie/fisheyes_fastapi
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
